# Generated by Django 3.1.2 on 2020-12-08 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metodo',
            name='Descripcion',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='metodo',
            name='Ejemplos_Practicos',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='metodo',
            name='ImagenDescripcion',
            field=models.ImageField(default=None, upload_to=None),
        ),
        migrations.AddField(
            model_name='metodo',
            name='ImagenEjemplos_Practicos',
            field=models.ImageField(default=None, upload_to=None),
        ),
        migrations.AddField(
            model_name='metodo',
            name='ImagenIntroduccion',
            field=models.ImageField(default=None, upload_to=None),
        ),
        migrations.AddField(
            model_name='metodo',
            name='Introduccion',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='practica',
            name='Contenido',
            field=models.TextField(default=None),
        ),
    ]
